name: bornomala
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  get_cli: ^1.7.1
  animated_text_kit: ^4.2.1
  bouncing_widget: ^2.0.0


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true



